#!/bin/sh
echo "compiling LearnCode"
g++ -o learn LearnCode.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling receiver"
g++ -o receiver ShowReceivedCode.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling kaku"
g++ -o kaku kaku.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling kakunew"
g++ -o kakunew kakunew.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling pair"
g++ -o pair pair.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "changing permission"
chmod +s kakunew
chmod +s pair
chmod u+s kaku
