var fake=0,w_url=location.host,w_svr="LamPI-daemon.php",w_port="5000",w_uri,w_sock,w_tcnt=0,phonegap=0,jqmobile=0,murl="",skin="",debug="1",persist="1",mysql="1",cntrl="1",s_screen="room",s_controller=murl+"backend_rasp.php",s_room_id=1,s_scene_id=1,s_timer_id=1,s_handset_id=1,s_weather_id=1,s_setting_id="1",s_recorder="",s_recording=0,max_rooms=16,max_scenes=16,max_devices=16,max_timers=16,max_handsets=8,max_weather=4,rooms={},devices={},moods={},scenes={},timers={},settings={},brands={},handsets=
{};
function start_LAMP(){$(window).load(function(){function d(){alert("onLine")}function b(){alert("onDeviceReady")}function a(){w_uri="ws://"+w_url+":"+w_port;w_sock=new WebSocket(w_uri);w_sock.onopen=function(a){console.log("Websocket:: Opening socket "+w_uri)};w_sock.onclose=function(a){console.log("Websocket:: socket closed, reopening socket "+w_uri);w_sock=new WebSocket(w_uri)};w_sock.onerror=function(a){a=w_sock.readyState;console.log("Websocket:: error. State is: "+a);message("websocket:: error: "+a,
1)};w_sock.onmessage=function(a){a.data.substr(1);a=JSON.parse(a.data);var b=a.tcnt,d=a.type,g=a.action;switch(g){case "ack":1<debug?message("action: "+g+", tcnt: "+b+", mes: "+c+", type: "+d):console.log("action: "+g+", tcnt: "+b+", mes: "+c+", type: "+d);break;case "upd":case "gui":message("action: "+g+", tcnt: "+b+", mes: "+c+", type: "+d);switch(d){case "json":console.log("onmessage:: read upd message. Type is: "+d+". Json is not supported yet");c=a.val;break;case "raw":var c=a.message;console.log("onmessage:: read upd message. Type is: "+
d);d=parse_int(c);"!R"==c.substr(0,2)&&(a=d[0],b=d[1],c.search("FdP"),c=d[2],d=find_device(a,"D"+b),console.log("onmessage:: room: "+a+", device: "+b+", val: "+c+", ind: "+d),devices[d].val=c,a==s_room_id&&"room"==s_screen&&activate_room(s_room_id));break;default:console.log("onmessage:: read upd message. Unknown type: "+d)}break;case "weather":c=a.address;b=a.channel;d=a.temperature;a=a.humidity;message("Weather:: addr: "+c+", chl: "+b+", temp: "+d+", humi: "+a+"%");console.log("Weather:: addr: "+
c+", chl: "+b+", temp: "+d+", humi: "+a+"%");break;case "sensor":console.log("Lampi.js:: received sensor message");break;case "energy":console.log("Lampi.js:: received energy message");break;default:message("Unknown message: action: "+g+", tcnt: "+b+", mes: "+c+", type: "+d)}};console.log("Websocket:: readyState: "+w_sock.readyState)}function c(){var b=window.localStorage.getItem("uname"),d=window.localStorage.getItem("pword"),c=window.localStorage.getItem("saddr"),g;g+='<div data-role="popup" id="loginpopup" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;"><div data-role="header" data-theme="a">';
g+="<h1>User Access</h1>";g+="</div>";g+='<div role="main" class="ui-content">';g+="<fieldset>";g+='<label for="saddr" class="ui-hidden-accessible pops">Server IP</label>';g=null!==c?g+('<input type="text" name="saddr" id="saddr" value="'+c+'"><br/>'):g+'<input type="text" name="saddr" id="saddr" placeholder="server ip"><br/>';g+='<label for="uname" class="ui-hidden-accessible pops">Username</label>';g=null!==b?g+('<input type="text" name="uname" id="uname" value="'+b+'"><br/>'):g+'<input type="text" name="uname" id="uname" placeholder="username"><br/>';
g+='<label for="pword" class="ui-hidden-accessible pops">Password</label>';g=null!==d?g+('<input type="password" name="pword" id="pword" value="'+d+'"><br/>'):g+'<input type="password" name="pword" id="pword" placeholder="pin"><br/>';g+="</fieldset>";g+='<input type="submit" id="cancelSubmit" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Cancel</a>';g+='<input type="submit" id="loginSubmit" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Submit</a>';
g+="</div>";g+="</div>";$("#popup").append(g);$("#loginpopup").popup();$("#loginpopup").popup("open");$("#loginSubmit").click(function(g,k){console.log("login");c=$("#saddr").val();b=$("#uname").val();d=$("#pword").val();window.localStorage.setItem("uname",b);window.localStorage.setItem("pword",d);window.localStorage.setItem("saddr",c);console.log("popup closed with ip: "+c);murl="http://"+c+"/";s_controller=murl+"backend_rasp.php";1!=phonegap&&a();0>load_database("init")&&alert("Error:: Loading Database Failed");
$("#loginpopup").popup("destroy")});$("#cancelSubmit").click(function(b,e){alert("Cancel, assume we have defult values ...");murl="http://"+c+"/";s_controller=murl+"backend_rasp.php";0>load_database("init")&&alert("Error:: Loading Database Failed");1!=phonegap&&a();$("#loginpopup").popup("close");return!1})}1==jqmobile?(1==phonegap&&(document.addEventListener("deviceready",b,!1),document.addEventListener("online",d,!1)),c()):(0>load_database("init")&&alert("Error:: loading database failed"),1==settings[1].val&&
1!=phonegap&&a());$("#gui_header").on("click",".hr_button",function(a){a.preventDefault();selected=$(this);value=$(this).val();id=$(a.target).attr("id");$(".hr_button").removeClass("hover");$(this).addClass("hover");activate_room(id)});$("#gui_header").on("click",".cr_button",function(a){a.preventDefault();selected=$(this);$(".cr_button").removeClass("hover");$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");switch(id){case "Add":for(var b=1;b<=max_rooms;){for(a=0;a<rooms.length&&
rooms[a].id!=b;a++);if(a==rooms.length)break;b++}if(b>max_rooms)return alert("Unable to add more rooms"),-1;2<debug&&alert("Add Room: New index found: "+b);askForm("<form><fieldset><p>You have created room nr "+b+'. Please specify name for your new room</p><label for="val_1">Name: </label><input type="text" name="val_1" id="val_1" value="" class="text ui-widget-content ui-corner-all" /></fieldset></form>',function(a){2<debug&&alert(" Dialog returned Name,Type: "+a);a={id:b,name:a[0]};rooms.push(a);
s_room_id=b;console.log(a);send_2_dbase("add_room",a);init_rooms("init");return 1},function(){activate_room(s_room_id);return 1},"Confirm Create");break;case "Del":var d='<label for="val_1">Delete Room: </label><select id="val_1" value="val_1" >';for(a=0;a<rooms.length;a++)d+="<option>"+rooms[a].name+"</option>";a="<form><fieldset><br />You are planning to delete a room from the system. If you do so, all actions associated with the room must be deleted too.\nPlease start with selecting a room from the list on top of the screen.Please click on the room you wish to delete from the system.<br /><br />"+
(d+"</select>")+"<br /></fieldset></form>";askForm(a,function(a){2<debug&&alert(" Dialog returned val_1,val_2: "+a);for(var b=a[0],e=0;e<rooms.length&&rooms[e].name!=b;e++);a=rooms[e].id;for(var d=0;d<devices.length;d++)if(devices[d].room==a)return alert("Room "+b+" is not empty\nWe cannot delete this room\nSorry"),0;b=rooms.splice(e,1);s_room_id==a&&(s_room_id=rooms[0].id);0<persist&&(console.log(b[0]),send_2_dbase("delete_room",b[0]),1<debug&&alert("Removed from dbase:: id: "+b[0].id+" , name: "+
b[0].name));init_rooms("init");return 1},function(){activate_room(s_room_id);return 1},"Confirm Delete Room");break;case "Help":alert("This form allows you to control the lighting in a particular room Select the room that you like to control with the buttons in the top header area For every device in the room, whether dimmer or switch, users can change the light setting.\nThe small buttons in the top right corner are special buttons The leftmost green one allows you to add a device to the active room.\nThe red X allows you to delete a device from the room. Press the X and you'll see small selection buttons on the left of every device line. Press one and you'll be able to delete the device"),
$(".cr_button").removeClass("hover")}});$("#gui_header").on("click",".hs_button",function(a){a.preventDefault();selected=$(this);$(".hs_button").removeClass("hover");$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");activate_scene(id)});$("#gui_header").on("click",".cs_button",function(a){a.preventDefault();selected=$(this);$(".cs_button").removeClass("hover");$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");switch(id){case "Add":for(var b=1;b<=max_scenes;){for(a=
0;a<scenes.length&&scenes[a].id!=b;a++);if(a==scenes.length)break;b++}if(b>max_scenes)return alert("Unable to add more scenes"),-1;askForm("<form><fieldset><p>You have created scene nr "+b+'. Please specify name for your new scene</p><label for="val_1">Name: </label><input type="text" name="val_1" id="val_1" value="" class="text ui-widget-content ui-corner-all" /><br /></fieldset></form>',function(a){2<debug&&alert(" Dialog returned val_1,val_2: "+a);a={id:b,name:a[0],val:"OFF",seq:""};scenes.push(a);
send_2_dbase("add_scene",a);s_scene_id=b;init_scenes("init");return 1},function(){activate_scene(s_scene_id);return 1},"Confirm Create");break;case "Del":var d='<label for="val_1">Delete Scene: </label><select id="val_1" value="val_1" >';for(a=0;a<scenes.length;a++)d+="<option>"+scenes[a].name+"</option>";a="<form><fieldset><br />You are planning to delete a scene from the system. If you do so, all actions associated with the scene must be deleted too.\nPlease start with selecting a scene from the list.<br /><br />"+
(d+"</select>")+"<br /></fieldset></form>";askForm(a,function(a){2<debug&&alert(" Dialog returned val_1,val_2: "+a);a=a[0];for(var b=0;b<scenes.length&&scenes[b].name!=a;b++);a=scenes.splice(b,1);0<persist&&(console.log(a[0]),send_2_dbase("delete_scene",a[0]),1<debug&&alert("Removed from dbase:: id: "+a[0].id+" , name: "+a[0].name));s_scene_id=scenes[0].id;init_scenes("init");return 1},function(){activate_scene(s_scene_id);return 1},"Confirm Delete Scene");break;case "Help":alert("This is the Help screen for Scenes (or sequences if you wish)\n\nIn the header section you see an overview of your scenes defined, which enables you to view/change or add to a scene of your choice. \n\nThe Context section in the middle shows for each defines scene the sequence of actions that will be performed when you RUN that scene with the blue > button. \nIf you add or remove a device action to a scene this will NOT be stored unless you use the store function which will write the sequence to the database. ");
$(".cs_button").removeClass("hover");break;default:alert("Error:: click id "+id+" not recognized")}1!=jqmobile&&$("#gui_header tbody").sortable({start:function(a,b){$(b.item).data("startindex",b.item.index())},stop:function(a,b){$("#gui_devices tr").each(function(a){0!=a?console.log(a+": "+$(this).children().children(".dlabels").attr("id")):console.log(a+": Header")})}}).disableSelection()});$("#gui_header").on("click",".ht_button",function(a){a.preventDefault();selected=$(this);$(".ht_button").removeClass("hover");
$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");activate_timer(id);2<debug&&alert("init_timer:: Button event")});$("#gui_header").on("click",".ct_button",function(a){a.preventDefault();selected=$(this);$(".cs_button").removeClass("hover");$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");switch(id){case "Add":for(var b=1;b<=max_timers;){for(a=0;a<timers.length&&timers[a].id!=b;a++);if(a==timers.length)break;b++}if(b>max_timers)return alert("Unable to add more timers"),
-1;askForm("<form><fieldset><p>You have created timer nr"+b+'. Please specify name for your new timer</p><label for="val_1">Name: </label><input type="text" name="val_1" id="val_1" value="" class="text ui-widget-content ui-corner-all" /><br /></fieldset></form>',function(a){2<debug&&alert(" Dialog returned val_1,val_2: "+a);a={id:b,name:a[0],scene:"",tstart:"00:00:00",startd:"01/01/13",endd:"",days:"mtwtfss",months:"jfmamjjasond"};timers.push(a);send_2_dbase("add_timer",a);init_timers("init");return 1},
function(){activate_timer(s_timer_id);return 1},"Confirm Create");break;case "Del":var d='<label for="val_1">Delete Timer: </label><select id="val_1" value="val_1" >';for(a=0;a<timers.length;a++)d+="<option>"+timers[a].name+"</option>";a="<form><fieldset><br />You are planning to delete a timer from the system. If you do so, all actions associated with the timer are deleted too.\nPlease start with selecting a timer from the list.<br /><br />"+(d+"</select>")+"<br /></fieldset></form>";askForm(a,function(a){2<
debug&&alert(" Dialog returned val_1,val_2: "+a);a=a[0];for(var b=0;b<timers.length&&timers[b].name!=a;b++);a=timers.splice(b,1);0<persist&&(console.log(a[0]),send_2_dbase("delete_timer",a[0]),1<debug&&alert("Removed from dbase:: id: "+a[0].id+" , name: "+a[0].name));init_timers("init");return 1},function(){activate_timer(s_timer_id);return 1},"Confirm Delete Timer");break;case "Help":alert("This is the Help screen for Timers\n\nIn the header section you see an overview of your timers defined, selecting one enables you to view/change or add to a timer. \n\nThe Content section in the middle shows its settings: Which scene should be started, on what time, and on whichs days or months. \nIf you change a timer setting this will NOT be stored unless you use the store function which will write the timer to the database. ");
$(".ct_button").removeClass("hover");break;default:alert("Error:: click id "+id+" not recognized")}});$("#gui_header").on("click",".hh_button",function(a){a.preventDefault();selected=$(this);value=$(this).val();id=$(a.target).attr("id");$(".hh_button").removeClass("hover");$(this).addClass("hover");activate_handset(id)});$("#gui_header").on("click",".ch_button",function(a){a.preventDefault();selected=$(this);$(".cs_button").removeClass("hover");$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");
switch(id){case "Add":for(var b=1;b<=max_handsets;){for(a=0;a<handsets.length&&handsets[a].id!=b;a++);if(a==handsets.length)break;b++}if(b>max_handsets)return alert("Unable to add more handsets"),-1;askForm("<form><fieldset><br />DRAFT:<p>You have created handset nr "+b+'. Please specify name for your new remote</p><label for="val_1">Name: </label><input type="text" name="val_1" id="val_1" value="" class="text ui-widget-content ui-corner-all" /><br /><br /><label for="val_2">Address: </label><input type="text" name="val_2" id="val_2" value="" class="text ui-widget-content ui-corner-all" /><br /></fieldset></form>',
function(a){2<debug&&alert(" Dialog returned val_1,val_2: "+a);var d=a[0];a=a[1];for(var c=0;c<handsets.length&&handsets[c].addr!=a;c++);if(c!=handsets.length)return alert("The handset address "+a+" is already registered"),0;1<debug&&alert("New handset on ind: "+b+", name: "+d+", addr: "+a);d={id:b,name:d,brand:"",addr:a,unit:"0",val:"0",type:"switch",scene:""};handsets.push(d);console.log("Added new handset "+d.name);send_2_dbase("add_handset",d);s_handset_id=b;init_handsets("init");return 1},function(){activate_handset(s_handset_id);
return 1},"Confirm Create");break;case "Del":var d='<label for="val_1">Delete Handset: </label><select id="val_1" value="val_1" >',c=[];for(a=0;a<handsets.length;a++)-1==$.inArray(handsets[a].id,c)&&(d+="<option>"+handsets[a].name+"</option>",c[c.length]=handsets[a].id);a="<form><fieldset><br>DRAFT:</br><br />You are planning to delete a handset from the system. If you do so, all actions associated with the handset must be deleted too.\nPlease start with selecting a handset from the list.<br /><br />"+
(d+"</select>")+"<br /></fieldset></form>";askForm(a,function(a){2<debug&&alert(" Dialog returned val_1,val_2: "+a);a=a[0];for(var b=handsets.length-1;0<=b;b--)if(2<debug&&alert("working with i: "+b+", handset id: "+handsets[b].name),handsets[b].name==a){var d=handsets.splice(b,1);0<persist&&(console.log(d[0]),send_2_dbase("delete_handset",d[0]),1<debug&&myAlert("Removed from dbase:: id: "+d[0].id+" , name: "+d[0].name))}s_handset_id=handsets[0].id;init_handsets("init");return 1},function(){activate_handset(s_handset_id);
return 1},"Confirm Delete Handset");break;case "Help":alert("This is the Help screen for Handsets or Remote controls\n\nIn the header section you see an overview of your handsets defined, which enables you to view/change or add to a handset of your choice. \n\nThe Content section in the middle shows for each defined handset the button definitionsIf you add or remove a device action to a handset these will NOT be stored unless you use the store function which will write the sequence to the database. ");
$(".ch_button").removeClass("hover");break;default:alert("Error:: click id "+id+" not recognized")}1!=jqmobile&&$("#gui_header tbody").sortable({start:function(a,b){$(b.item).data("startindex",b.item.index())},stop:function(a,b){$("#gui_devices tr").each(function(a){0!=a?console.log(a+": "+$(this).children().children(".dlabels").attr("id")):console.log(a+": Header")})}}).disableSelection()});$("#gui_header").on("click",".hc_button",function(a){a.preventDefault();selected=$(this);$(".hc_button").removeClass("hover");
$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");activate_setting(id)});$("#gui_header").on("click",".cc_button",function(a){a.preventDefault();selected=$(this);$(".cc_button").removeClass("hover");$(this).addClass("hover");value=$(this).val();id=$(a.target).attr("id");switch(id){case "Add":alert("Add a Setting");break;case "Del":break;case "Help":alert("This is the Help screen for Setting Configuration\n\nIn the header section you see buttons to select a configuration item, each one will show a form where you can change certain settings. ");
$(".cc_button").removeClass("hover");break;default:alert("Error:: click id "+id+" not recognized")}})})}function message(d,b){2<debug&&alert("Message called: "+d+", lvl: "+b+", debug: "+debug);"undefined"==typeof b&&(b=debug);b<=debug&&($("#gui_messages").empty(""),d='<div id="comment">'+d+"</div>",$("#gui_messages").append(d));return 0}
function init(){debug=settings[0].val;cntrl=settings[1].val;s_controller=0==cntrl?murl+"backend_ics.php":murl+"backend_rasp.php";mysql=settings[2].val;persist=settings[3].val;1!=jqmobile&&(skin=settings[4].val,$("link[href^='styles']").attr("href",skin));init_rooms(s_room_id);init_menu(s_setting_id)}function getTime(){var d=new Date;return pad(d.getHours(),2)+":"+pad(d.getMinutes(),2)+":"+pad(d.getSeconds(),2)}function parse_int(d){return d.match(/\d+\.?\d*/g)}
function read_int(d){return d.match(/\d+\.?\d*/g)[0]}function myAlert(d,b){$('<div style="padding: 10px; min-width: 250px; max-width: 500px; word-wrap: break-word;">'+d+"</div>").dialog({draggable:!1,modal:!0,resizable:!1,width:"auto",title:b||"Confirm",minHeight:75,buttons:{OK:function(){$(this).dialog("destroy")}}})}
function myConfirm(d,b,a,c){$('<div style="padding: 10px; max-width: 500px; word-wrap: break-word;">'+d+"</div>").dialog({draggable:!1,modal:!0,resizable:!1,width:"auto",title:c||"Confirm",minHeight:75,buttons:{OK:function(){"function"==typeof b&&setTimeout(b,50);$(this).dialog("destroy")},Cancel:function(){"function"==typeof a&&setTimeout(a,50);$(this).dialog("destroy")}}})}
function checkLength(d,b,a,c){return d.val().length>c||d.val().length<a?(d.addClass("ui-state-error"),updateTips("Length of "+b+" must be between "+a+" and "+c+"."),!1):!0}
function askForm(d,b,a,c){1==jqmobile?($("#gui_content").append(d),$("#myform").popup(),$("#myform").popup("open"),$("#myform").on("popupafterclose",function(a,d){if("function"==typeof b){var c=[$("#val_1").val(),$("#val_2").val(),$("#val_3").val(),$("#val_4").val()];setTimeout(function(){b(c)},50)}})):$('<div style="padding: 10px; max-width: 500px; word-wrap: break-word;">'+d+"</div>").dialog({draggable:!1,modal:!0,resizable:!1,width:"auto",title:c||"Confirm",minHeight:120,buttons:{OK:function(){if("function"==
typeof b){var a=[$("#val_1").val(),$("#val_2").val(),$("#val_3").val(),$("#val_4").val()];setTimeout(function(){b(a)},50)}$(this).dialog("destroy")},Cancel:function(){"function"==typeof a&&setTimeout(a,50);$(this).dialog("destroy")}},close:function(){$(this).dialog("destroy")}})}
function init_rooms(d){$("#gui_header").empty();$("#gui_header").append('<table border="0">');d=$("#gui_header").children();var b;b='<tr class="rroom"><td>';for(var a=0;a<rooms.length;a++)room_name=rooms[a].name,room_id=rooms[a].id,b=room_id==s_room_id?b+room_button(room_id,room_name,"hover"):b+room_button(room_id,room_name);b+="</td><td>";b+='<input type="submit" id="Add" value= "+"  class="cr_button new_button">';b+='<input type="submit" id="Del" value= "X"  class="cr_button del_button">';b+='<input type="submit" id="Help" value= "?" class="cr_button help_button">';
b+="</td>";$(d).append(b);s_screen="room";activate_room(s_room_id)}
function init_scenes(d){$("#gui_header").empty();$("#gui_header").append('<table border="0">');d=$("#gui_header").children();var b="Init Scenes, scenes read: ",a;a='<tr class="rroom"><td>';for(var c=0;c<scenes.length;c++){var e=scenes[c].id,f=scenes[c].name,b=b+(c+", ");a=e==s_scene_id?a+scene_button(e,f,"hover"):a+scene_button(e,f)}a+="</td>";1<debug&&message(b);a+='<td><input type="submit" id="Add" value= "+" class="cs_button new_button">';a+='<input type="submit" id="Del" value= "X" class="cs_button del_button">';
a+='<input type="submit" id="Help" value= "?" class="cs_button help_button">';a+="</td>";$(d).append(a);s_screen="scene";activate_scene(s_scene_id)}
function init_timers(d){$("#gui_header").empty();$("#gui_header").append('<table border="0">');d=$("#gui_header").children();var b="Init Timers, timers read: ",a;a='<tr class="rroom"><td>';for(var c=0;c<timers.length;c++){var e=timers[c].id,f=timers[c].name,b=b+(c+", ");a=e==s_timer_id?a+timer_button(e,f,"hover"):a+timer_button(e,f)}1<debug&&message(b);a+="</td><td>";a+='<input type="submit" id="Add" value= "+" class="ct_button new_button">';a+='<input type="submit" id="Del" value= "X" class="ct_button del_button">';
a+='<input type="submit" id="Help" value= "?" class="ct_button help_button">';a+="</td>";$(d).append(a);s_screen="timer";activate_timer(s_timer_id)}
function init_handsets(d){$("#gui_header").empty();$("#gui_header").append('<table border="0">');d=$("#gui_header").children();var b="Init Handsets, handsets read: ",a;a='<tr class="rroom"><td>';for(var c=[],e=0;e<handsets.length;e++)if(-1==$.inArray(handsets[e].id,c)){var f=handsets[e].id,h=handsets[e].name,b=b+(e+", ");a=f==s_handset_id?a+handset_button(f,h,"hover"):a+handset_button(f,h);c[c.length]=handsets[e].id}1<debug&&message(b);a+="</td><td>";a+='<input type="submit" id="Add" value= "+" class="ch_button new_button">';
a+='<input type="submit" id="Del" value= "X" class="ch_button del_button">';a+='<input type="submit" id="Help" value= "?" class="ch_button help_button">';a+="</td>";$(d).append(a);s_screen="handset";activate_handset(s_handset_id)}
function init_settings(d){$("#gui_header").empty();$("#gui_header").append('<table border="0">');d=$("#gui_header").children();var b="Init Config, config read: ",a;a='<tr class="rroom"><td>';for(var c=0;c<settings.length;c++){var e=settings[c].id,f=settings[c].name,b=b+(c+", ");a=e==s_setting_id?a+setting_button(e,f,"hover"):a+setting_button(e,f)}1<debug&&message(b);a+="</td><td>";a+='<input type="submit" id="Help" value= "?" class="cc_button help_button">';a+="</td>";$(d).append(a);s_screen="config";
activate_setting(s_setting_id)}
function init_menu(d){html_msg='<table border="0">';$("#gui_menu").append(html_msg);d=$("#gui_menu").children();var b=1==jqmobile?'<tr><td><input type="submit" id="M1" value= "Rooms" class="hm_button hover"><input type="submit" id="M2" value= "Scenes" class="hm_button"><input type="submit" id="M3" value= "Timers" class="hm_button"><input type="submit" id="M4" value= "Handsets" class="hm_button"><input type="submit" id="M5" value= "Config" class="hm_button"></td></tr>':'<tr class="switch"><td><input type="submit" id="M1" value= "Rooms" class="hm_button hover"></td><tr class="switch"><td><input type="submit" id="M2" value= "Scenes" class="hm_button"></td><tr class="switch"><td><input type="submit" id="M3" value= "Timers" class="hm_button"></td><tr class="switch"><td><input type="submit" id="M4" value= "Handsets" class="hm_button"></td><tr><td></td><tr><td></td><tr class="switch"><td><input type="submit" id="M5" value= "Config" class="hm_button"></td>';
$(d).append(b);$("#gui_menu").on("click",".hm_button",function(a){a.preventDefault();selected=$(this);value=$(this).val();id=$(a.target).attr("id");$(".hm_button").removeClass("hover");$(this).addClass("hover");switch(id){case "M1":init_rooms("init");break;case "M2":init_scenes(s_scene_id);break;case "M3":init_timers();break;case "M4":init_handsets();break;case "M5":init_settings();break;default:message("init_menu:: id: "+id+" not a valid menu option")}})}
function activate_room(d,b){for(var a,c,e=0;e<rooms.length;e++)if(rooms[e].id==d){c=rooms[e].name;break}$("#gui_content").empty();a='<div id="gui_devices"></div>';$("#gui_content").append(a);a='<table border="0">';$("#gui_devices").append(a);var e=$("#gui_devices").children(),f='<thead><tr class="switch">',f=("Del"==b?f+'<td colspan="2">':f+"<td>")+'<input type="submit" id="Rx" value="X" class="dbuttons del_button" ><input type="submit" id="Ra" value="+" class="dbuttons new_button" ></td>',f=f+('<td class="filler" align="center">'+
c+"</td>");1==jqmobile?f+='<td><input type="submit" id="Fa" value="ALL OFF" class="dbuttons" ></td>':(f+="<td></td>",f+='<td colspan="2"><input type="submit" id="Fa" value="ALL OFF" class="dbuttons" ></td>');$(e).append(f);$(e).append("</tr>");a="</thead><tbody>";$(e).append(a);for(var e=$("#gui_devices tbody").last(),h=0;h<devices.length;h++){var g=devices[h].id,n=devices[h].room;if(n==d){c=devices[h].name;var k=devices[h].type,f=devices[h].val,m;0==f?(a=" hover",m=""):(a="",m=" hover");switch(k){case "switch":1==
jqmobile?(f='<tr class="devrow switch">',"Del"==b&&(f+='<td><input type="checkbox" id="'+g+'c" name="cb'+g+'" value="yes" class="dbuttons"></td>'),f+='<td colspan="2"><input type="text" id="'+g+'" value="'+c+'" class="dlabels"></td>',f+='<td><input type="submit" id="'+g+'F0" value="OFF" class="dbuttons'+a+'">',f+='<input type="submit" id="'+g+'F1" value="ON" class="dbuttons'+m+'"></td>'):(f='<tr class="devrow switch">',"Del"==b&&(f+='<td><input type="checkbox" id="'+g+'c" name="cb'+g+'" value="yes" class="dbuttons"></td>'),
f+='<td colspan="2"><input type="submit" id="'+g+'" value= "'+c+'" class="dlabels"></td>',f+="<td></td>",f+='<td><input type="submit" id="'+g+'F0" value= "OFF" class="dbuttons'+a+'"></td>',f+='<td><input type="submit" id="'+g+'F1" value= "ON" class="dbuttons'+m+'"></td>');$(e).append(f);break;case "dimmer":1==jqmobile?(k='<tr class="devrow dimrow">',"Del"==b&&(k+='<td><input type="checkbox" id="'+g+'c" name="cb'+g+'" value="yes" class="dbuttons"></td>'),k+='<td colspan="2" ><label for="'+g+'Fd">'+
c+"</label>",k+='<input type="number" data-type="range" style="width:25px;" id="'+g+'Fd" name="'+g+'Fl" value="'+f+'" min=0 max=31 data-highlight="true" data-mini="false" data-theme="b" /></td>',k+='<td><input type="submit" id="'+g+'F0" value= "OFF" class="dbuttons'+a+'" />',k+='<input type="submit" id="'+g+'F1" value= "ON" class="dbuttons'+m+'" /></td>',k+="</tr>"):(k='<tr class="devrow dimrow">',"Del"==b&&(k+='<td><input type="checkbox" id="'+g+'c" name="cb'+g+'" value="yes" class="dbuttons"></td>'),
k+='<td><input type="submit" id="'+g+'" value= "'+c+'" class="dlabels"></td><td><div id="'+g+'Fd" class="slider"></div></td><td><input type="text" id="'+g+'Fl" class="slidval"></td><td><input type="submit" id="'+g+'F0" value="OFF" class="dbuttons'+a+'"></td><td><input type="submit" id="'+g+'F1" value="ON" class="dbuttons'+m+'"></td></tr>');e.append(k);var p="#"+g+"Fl",l="#"+g+"Fd";1==jqmobile?$(function(){var a=load_device(n,g);"F0"==a&&(a=0);$(l).slider({stop:function(a,b){var d=$(a.target).attr("id"),
c=$(a.target).val();0==c?(handle_device(d.slice(0,-2),"F"+c),$("#"+d.slice(0,-2)+"F1").removeClass("hover"),$("#"+d.slice(0,-2)+"F0").addClass("hover")):(handle_device(d,"P"+c),$("#"+d.slice(0,-2)+"F0").removeClass("hover"),$("#"+d.slice(0,-2)+"F1").addClass("hover"));store_device(s_room_id,d.slice(0,-2),c)}});$(l).slider("refresh")}):$(function(){var a=load_device(n,g);"F0"==a&&(a=0);$(l).slider({range:"max",main:1,min:0,max:32,value:a,slide:function(a,b){var d="#"+$(a.target).attr("id").slice(0,
-1)+"l";$(d).val(b.value)},stop:function(a,b){var d=$(a.target).attr("id"),c=b.value;0==c?(c=0,handle_device(d.slice(0,-2),"F"+c),$(this).parent().siblings().children().removeClass("hover"),$(this).parent().siblings().children("#"+d.slice(0,-2)+"F0").addClass("hover")):(handle_device(d,"P"+c),$(this).parent().siblings().children().removeClass("hover"),$(this).parent().siblings().children("#"+d.slice(0,-2)+"F1").addClass("hover"));store_device(s_room_id,d.slice(0,-2),c)}});$(p).val(a)});break;default:alert("lamp_button, type: "+
k+" unknown")}}}s_room_id=d;$("#gui_devices").on("click",".dbuttons",function(a){a.preventDefault();value=$(this).val();var c=$(a.target).attr("id");switch(c){case "Ra":2<debug&&alert("Room Add Button: "+c);for(var e=1;e<=max_devices;){for(a=0;a<devices.length&&(devices[a].room!=s_room_id||devices[a].id.substr(1)!=e);a++);if(a==devices.length)break;e++}1<debug&&alert("Add device:: room:"+s_room_id+", device: "+e+", devices.length: "+devices.length);c='<label for="val_3">  Select Brand: </label><select id="val_3" value="kaku">';
for(a=0;a<brands.length;a++)c+="<option>"+brands[a].name+"</option>";askForm('<form id="addRoomForm"><fieldset><p>You have created a new device, please give it a name and specify its type and brand. Optionally, the group address can be set if this device address is different from the room address</p><label for="val_1">Name: </label><input type="text" name="val_1" id="val_1" value="" class="text ui-widget-content ui-corner-all" /><br /><label for="val_2">Type: </label><select id="val_2" value="switch" ><option selected="selected">switch</option><option>dimmer</option></select><br />'+
(c+"</select>")+'<label for="val_4">Group addr: </label><input type="text" name="val_4" id="val_4" value="'+(Number(s_room_id)+99)+'" class="text ui-widget-content ui-corner-all" /></fieldset></form>',function(a){2<debug&&alert(" Dialog returned val_1,val_2,val_3: "+a);for(var b,d,c=0;c<brands.length;c++)brands[c].name==a[2]&&(b=brands[c].id,d=brands[c].fname);if("dimmer"==a[1]&&"kaku"!=d)return alert("Type dimmer is not supported for brand "+d),1;a={id:"D"+e,room:""+s_room_id+"",gaddr:a[3],name:a[0],
type:a[1],val:"0",lastval:"0",brand:b};devices.push(a);console.log(a);send_2_dbase("add_device",a);activate_room(s_room_id);return 1},function(){activate_room(d);return 1},"Confirm Create");return 1;case "Rx":return message('<p style="textdecoration: blink; background-color:yellow; color:black;">Click a button to delete ...</p>'),activate_room(d,"Del"),1;case "Fa":handle_device("","Fa");for(a=0;a<devices.length;a++)devices[a].room==s_room_id&&store_device(s_room_id,devices[a].id,"OFF");activate_room(s_room_id);
return 1}if("Del"==b&&"checkbox"==$(this).attr("type")){1>debug&&$("#gui_messages").empty();var f=c.slice(0,-1),g=find_device(s_room_id,f),m=$(this);message("Device to delete: id Name"+devices[g].name,0);myConfirm("You have selected device "+devices[g].name+" for deletion. Do you really want to delete this device?",function(){m.closest("tr").remove();var a=devices.splice(g,1);0<persist&&(console.log(a[0]),send_2_dbase("delete_device",a[0]),1<debug&&alert("Removed from dbase:: id: "+a[0].id+" , name: "+
a[0].name));1<debug&&alert("Removed object id:"+f);activate_room(d);return 1},function(){activate_room(d);return 1},"Confirm Delete");return 1}if("Sel"==b&&"checkbox"==$(this).attr("type"))return message("Device Add",1),alert("Device Add\nid: "+f),1;c=$(this).attr("id");f=c.slice(0,-2);value=$(this).val();handle_device(f,value);store_device(s_room_id,f,value);1==jqmobile?(c="0"==c.substr(-1,1)?c.slice(0,-1)+"1":c.slice(0,-1)+"0",$("#"+c).removeClass("hover")):$(this).parent().siblings().children().removeClass("hover");
$(this).addClass("hover");button_class=$(a.target).parent().parent().attr("class");"devrow dimrow"==button_class&&(a="#"+f+"Fd",value=load_device(s_room_id,f),"OFF"==value&&(value=0),1==jqmobile?($(a).val(value),$(a).slider("refresh")):($(a).slider("option","value",value),$("#"+f+"Fl").val(value)))});if(1!=jqmobile){var r;$("#gui_devices tbody").last().sortable({start:function(a,b){$(b.item).data("startindex",b.item.index());r=b.item.index();console.log("Start pos: "+r)},stop:function(a,b){var d=
b.item.index(),c,e;console.log("start_pos: "+r+", stop_pos: "+d);for(var f=h=0;f<devices.length;f++)devices[f].room==s_room_id&&(h==r?e=f:h==d&&(c=f),h++);console.log("room: "+s_room_id+",start_index: "+e+", stop_pos: "+c);d=devices.splice(e,1);console.log("name removed: "+d[0].name);devices.splice(c,0,d[0])}}).disableSelection()}}
function activate_scene(d){$("#gui_content").empty();html_msg='<div id="gui_scenes"></div>';$("#gui_content").append(html_msg);for(var b=0;b<scenes.length;b++){var a=scenes[b].id;if(d==a){2<debug&&alert("Activate_screen:: Making buttons for scene: "+a);html_msg='<table border="0">';$("#gui_scenes").append(html_msg);var c=$("#gui_scenes").children(),e=scenes[b].seq,f='<thead><tr class="switch"><td colspan="2"><input type="submit" id="Fx'+a+'" value="X" class="dbuttons del_button"><input type="submit" id="Fr'+
a+'" value="+" class="dbuttons new_button"><input type="submit" id="Fq'+a+'" value=">" class="dbuttons play_button"></td><td colspan="2"><input type="input"  id="Fl'+a+'" value= "'+scenes[b].name+'" class="dlabels"></td><td><input type="submit" id="Fc'+a+'" value="STOP" class="dbuttons"><input type="submit" id="Fe'+a+'" value="Store" class="dbuttons"></td></thead>';$(c).append(f);$(c).append("<tbody>");if(""!=e)for(var h=e.split(","),e=0;e<h.length;e+=2){var g=e/2+1,f=decode_scene_string(h[e]);decode_scene_string(h[e+
1]);f='<tr class="scene"><td><input type="checkbox" id="s'+a+'c" name="cb'+g+'" value="yes"></td><td> '+g+'<td><input type="input" id="Fs'+a+"i"+g+'" value= "'+h[e]+'" class="dlabels sval"></td><td><input type="text" id="Ft'+a+"t"+g+'" value= "'+h[e+1]+'" class="dbuttons sval"></td><td>'+f;$(c).append(f)}else g=0;1==s_recording&&(f=decode_scene_string(s_recorder),console.log("Need to decode s_recorder"),s_recording=0,g++,f='<tr class="scene"><td><input type="checkbox" id="s'+a+'c" name="cb'+g+'" value="yes"></td><td>'+
g+'<td><input type="input" id="Fs'+a+"i"+g+'" value= "'+s_recorder+'" class="dlabels sval"></td><td><input type="text" id="Ft'+a+"t"+g+'" value= "00:00:10" class="dbuttons sval"></td><td colspan="2">'+f,$(c).append(f),scenes[b].seq=1==g?s_recorder+",00:00:10":scenes[b].seq+(","+s_recorder+",00:00:10"),2<debug&&alert("Recorder adding:: j: "+b+", s_scene_id: "+s_scene_id+"\n\n id: "+scenes[b].id+"\nval: "+scenes[b].val+"\n name: "+scenes[b].name+"\nseq: "+scenes[b].seq),send_2_dbase("upd_scene",scenes[b]),
message("Device command added to the scene"));$("#gui_scenes").on("click",".dbuttons",function(a){a.preventDefault();value=$(this).val();var b=$(a.target).attr("id"),c=get_scene(s_scene_id),e=c.seq.split(",");switch(b.substr(0,2)){case "Fq":var f='!FqP"'+c.name+'"';message_device("scene",f);break;case "Fe":f='!FeP"'+c.name+'"='+c.seq;send_2_dbase("upd_scene",c);message_device("scene",f);break;case "Fx":2<debug&&alert("Activate_screen:: Delete Fx button pressed");var g="Deleted actions ";$($("#gui_scenes .scene").get().reverse()).each(function(a){var b=
$(this).children().children(".dlabels").attr("id");a=parse_int(b)[1];$(this).children().children('input[type="checkbox"]').is(":checked")&&(1<debug&&alert("delete scene id: "+b+", index: "+a+" selected"),b=e.splice(2*(a-1),2),a--,1<debug&&alert("removed:"+b[0]+","+b[1]+": from seq: "+e),g+=a+" : "+decode_scene_string(b[0])+"; ")});message(g);for(c=0;c<scenes.length;c++)if(scenes[c].id==s_scene_id){"undefined"==typeof e?2<debug&&alert("activate_scene:: case FX: scene_split undefined"):(scenes[c].seq=
e.join(),2<debug&&alert("seq: "+scenes[c].seq));break}activate_scene(s_scene_id);break;case "Fc":f='!FcP"'+c.name+'"';alert("Cancel current Sequence: "+c.name+"\nScene cmd: "+f);message_device("scene",f);break;case "Fr":2<debug&&alert("Activate_screen:: Add Fr button pressed, start recording ...");myConfirm("You are about to add a new action to the scene. If you continue, the system will be in recording mode until you have selected a device action. Then you are returned to this scene screen again. Please confirm if you want to add a device. ",
function(){message('<p style="textdecoration: blink; background-color:red; color:white;">RECORDING</p>')},function(){s_recording=0;return 1},"Adding a Device action?");s_recording=1;s_recorder="";init_rooms("init");break;case "Ft":var h=$(a.target).val(),c="";for(i=0;24>i;i++)c=i==h.substr(0,2)?c+('<option selected="selected">'+("00"+i).slice(-2)+"</option>"):c+("<option>"+("00"+i).slice(-2)+"</option>");f="";for(i=0;60>i;i++)f=i==h.substr(3,2)?f+('<option selected="selected">'+("00"+i).slice(-2)+
"</option>"):f+("<option>"+("00"+i).slice(-2)+"</option>");var q="";for(i=0;60>i;i++)q=i==h.substr(6,2)?q+('<option selected="selected">'+("00"+i).slice(-2)+"</option>"):q+("<option>"+("00"+i).slice(-2)+"</option>");c='<form id="addRoomForm"><fieldset><p>You can change the timer settings for this action. Please use hh:mm:ss</p><br /><label style="width:50px;" for="val_1">hrs: </label><select id="val_1" value="'+h.substr(0,2)+'" >'+c+'</select><label style="width:50px;" for="val_2">mins: </label><select id="val_2" value="'+
h.substr(3,2)+'">'+f+'</select><label style="width:50px;" for="val_3">secs: </label><select id="val_3" selectedIndex="10" value="'+h.substr(6,2)+'">'+q+"</select></fieldset></form>";askForm(c,function(c){2<debug&&alert(" Dialog returned val_1,val_2,val_3: "+c);c=c[0]+":"+c[1]+":"+c[2];$(a.target).val(c);2<debug&&alert("Timer changed from "+h+" to: "+$(a.target).val());var f=parse_int(b)[1];e[2*(f-1)+1]=c;var g="";$("#gui_scenes .scene").each(function(a){var b=$(this).children().children(".dbuttons").attr("id"),
b=parse_int(b)[1];console.log("scn: "+d+" html index: "+a+" scene ind: "+b);g+=e[2*(b-1)]+","+e[2*(b-1)+1]+","});console.log("my_list :"+g);g=g.slice(0,-1);console.log("scene: "+s_scene_id+", "+scenes[s_scene_id-1].name+", my_list: "+g);scenes[s_scene_id-1].seq=g;2<debug&&alert("new scene_list:: "+g);return 0},function(){return 1},"Confirm Change");break;default:alert("Sequence action unknown: "+b.substr(-2))}})}}1!=jqmobile&&$("#gui_scenes tbody").sortable({start:function(a,b){$(b.item).data("startindex",
b.item.index())},stop:function(a,b){var c="";$("#gui_scenes .scene").each(function(a){var b=$(this).children().children(".dbuttons").attr("id").substr(4);console.log("scn: "+d+" html index: "+a+" scene ind: "+b);c+=h[2*(b-1)]+","+h[2*(b-1)+1]+","});console.log("my_list :"+c);c=c.slice(0,-1);console.log("scene: "+d+", "+scenes[d-1].name+", my_list: "+c);scenes[d-1].seq=c}}).disableSelection();s_scene_id=d}
function activate_handset(d){$("#gui_content").empty();html_msg='<div id="gui_handsets"></div>';$("#gui_content").append(html_msg);for(var b,a=b=0;a<handsets.length;a++){var c=handsets[a].id;if(d==c){2<debug&&alert("Activate_handset:: Making buttons for handset: "+c);var e=handsets[a].name,f=handsets[a].scene,h=handsets[a].addr,g=handsets[a].unit,n=handsets[a].val;if(0==b){html_msg='<table border="0">';$("#gui_handsets").append(html_msg);var k=$("#gui_handsets").children(),m='<thead><tr class="switch"><td colspan="2"><input type="submit" id="Fx'+
c+'" value="X" class="dbuttons del_button"><input type="submit" id="Fr'+c+'" value="+" class="dbuttons new_button"></td><td colspan="2"><input type="input"  id="Fl'+c+'" value= "'+e+'" class="dlabels"> addr: '+h+'</td><td><input type="submit" id="Fe'+c+'" value="Store" class="dbuttons"></td></thead>';$(k).append(m);$(k).append("<tbody>");b=1}if(""!=f)for(e=f.split(","),h=0;h<e.length;h+=2){var p=h/2+1,m=0==n?"off":"on",l=decode_scene_string(e[h]);decode_scene_string(e[h+1]);m='<tr class="handset"><td><input type="checkbox" id="s'+
c+'c" name="cb'+p+'" value="yes"></td><td>But '+g+" "+m+'</td><td><input type="input" id="Fs'+c+"u"+g+"v"+n+"i"+p+'" value= "'+e[h]+'" class="dlabels sval"></td><td><input type="text" id="Ft'+c+"u"+g+"v"+n+"i"+p+'" value= "'+e[h+1]+'" class="dbuttons sval"></td><td>'+l;$(k).append(m)}else p=0;1==s_recording&&(l=decode_scene_string(s_recorder),console.log("Decode s_recorder to: "+l),s_recording=0,p++,m='<tr class="handset"><td><input type="checkbox" id="s'+c+'c" name="cb'+p+'" value="yes"></td><td>But '+
p+'<td><input type="input" id="Fs'+c+"u"+g+"v"+n+"i"+p+'" value= "'+s_recorder+'" class="dlabels sval"></td><td><input type="text" id="Ft'+c+"u"+g+"v"+n+"i"+p+'" value= "00:00:10" class="dbuttons sval"></td><td colspan="2">'+l,$(k).append(m),handsets[a].scene=1==p?s_recorder+",00:00:10":handsets[a].scene+(","+s_recorder+",00:00:10"),2<debug&&alert("Recorder adding:: j: "+a+", s_handset_id: "+s_handset_id+"\n\n id: "+handsets[a].id+"\nval: "+handsets[a].val+"\n name: "+handsets[a].name+"\nseq: "+handsets[a].scene),
send_2_dbase("upd_scene",handsets[a]),message("Device command added to the scene",1))}}$("#gui_handsets").on("click",".dbuttons",function(a){a.preventDefault();value=$(this).val();var b=$(a.target).attr("id");parse_int(b);switch(b.substr(0,2)){case "Fe":for(var d=get_handset(s_handset_id),c=d.name,e=0;e<handsets.length;e++)handsets[e].id==s_handset_id&&(console.log("Fe Storing handset:: "+c+":"+handsets[e].unit+":"+handsets[e].val),send_2_dbase("store_handset",handsets[e]));break;case "Fx":2<debug&&
alert("Activate_handset:: Delete Fx button pressed");var g="Deleted actions ";0<debug&&myConfirm("You are about to delete one or more button actions for this handset. If you continue, all lines that you checked will be deleted from the system and this will be synchronized with the database.\nPlease keep in mind that you will delete ALL lines that you checked and and its corresponding actions ",function(){$($("#gui_handsets .handset").get().reverse()).each(function(a){var b=$(this).children().children(".dlabels").attr("id"),
e=$(this).children().children(".dlabels").attr("value"),h=parse_int(b)[0],k=parse_int(b)[1],n=parse_int(b)[2],l=parse_int(b)[3];d=get_handset_record(h,k,n);f=d.scene;var m=f.split(","),l=m.indexOf(e);if($(this).children().children('input[type="checkbox"]').is(":checked"))for(1<debug&&alert("delete handset button: "+c+"\nid: "+b+", scene ind: "+l+" selected, index: "+a+"\nHandset id: "+h+", unit: "+k+", val: "+n+"\nScene: "+f),a=m.splice(l,2),l--,1<debug&&alert("removed:"+a[0]+","+a[1]+": from seq: "+
m),g+=l+" : "+decode_scene_string(a[0])+"; ",l=0;l<handsets.length;l++)if(handsets[l].id==h&&handsets[l].unit==k&&handsets[l].val==n){"undefined"==typeof m?2<debug&&alert("activate_handset:: case FX: handset_split undefined"):(handsets[l].scene=m.join(),2<debug&&alert("scene: "+handsets[l].scene));break}});message(g);activate_handset(s_handset_id)},function(){activate_handset(s_handset_id);return 0},"Continue Deleting Handet(s)?");break;case "Fr":0<=debug&&myConfirm("You are about to add one or more button actions for this handset. If you continue, the system will add a new record AFTER a line that you checked. Please do not check more than one line if you're adding actions. The system will take the first line ONLY and discard other lines that are checked. \nI you like to add new buttons, just check nothing and let the system guide you to selecting a new button and a new action to the handset.",
function(){},function(){return 0},"\tContinue Adding Handet(s)?");2<debug&&alert("Activate_handset:: Add Fr button pressed, start recording ...");myConfirm("You are about to add an action to this handset. If you continue, the system will be in recording mode until you have selected a device action. Then you are returned to this scene screen again. Please confirm if you want to add a device. ",function(){message('<p style="textdecoration: blink; background-color:red; color:white;">RECORDING</p>');
s_recording=1;s_recorder="";init_handsets("init")},function(){s_recording=0;return 1},"Adding a Device action?");break;case "Ft":var h=$(a.target).val(),e="";for(i=0;24>i;i++)e=i==h.substr(0,2)?e+('<option selected="selected">'+("00"+i).slice(-2)+"</option>"):e+("<option>"+("00"+i).slice(-2)+"</option>");var k="";for(i=0;60>i;i++)k=i==h.substr(3,2)?k+('<option selected="selected">'+("00"+i).slice(-2)+"</option>"):k+("<option>"+("00"+i).slice(-2)+"</option>");var n="";for(i=0;60>i;i++)n=i==h.substr(6,
2)?n+('<option selected="selected">'+("00"+i).slice(-2)+"</option>"):n+("<option>"+("00"+i).slice(-2)+"</option>");e='<form id="addRoomForm"><fieldset><p>You can change the timer settings for this action. Please use hh:mm:ss</p><br /><label style="width:50px;" for="val_1">hrs: </label><select id="val_1" value="'+h.substr(0,2)+'" >'+e+'</select><label style="width:50px;" for="val_2">mins: </label><select id="val_2" value="'+h.substr(3,2)+'">'+k+'</select><label style="width:50px;" for="val_3">secs: </label><select id="val_3" selectedIndex="10" value="'+
h.substr(6,2)+'">'+n+"</select></fieldset></form>";askForm(e,function(d){2<debug&&alert(" Dialog returned val_1,val_2,val_3: "+d);d=d[0]+":"+d[1]+":"+d[2];$(a.target).val(d);2<debug&&alert("Timer changed from "+h+" to: "+$(a.target).val());var c=parse_int(b),e;for(e=0;e<handsets.length&&(handsets[e].id!=c[0]||handsets[e].unit!=c[1]||handsets[e].val!=c[2]);e++);var c=handsets[e].scene.split(","),f=$(a.target).attr("id"),g="Fs"+f.substr(2),l=$("#"+g).val();alert("tid: "+f+", sid: "+g+", sval: "+l);
f=c.indexOf(l);alert("split ind: "+f);c[f+1]=d;handsets[e].scene=c.join();return 0},function(){return 1},"Confirm Change");break;default:alert("Sequence action unknown: "+b.substr(-2))}});1!=jqmobile&&$("#gui_handsets tbody").sortable({start:function(a,b){$(b.item).data("startindex",b.item.index())},stop:function(a,b){var c="";$("#gui_handsets .scene").each(function(a){var b=$(this).children().children(".dbuttons").attr("id").substr(4);console.log("scn: "+d+" html index: "+a+" scene ind: "+b);c+=
scene_split[2*(b-1)]+","+scene_split[2*(b-1)+1]+","});console.log("my_list :"+c);c=c.slice(0,-1);console.log("scene: "+d+", "+handsets[d-1].name+", my_list: "+c);handsets[d-1].scene=c}}).disableSelection();s_handset_id=d}
function activate_timer(d){2<debug&&alert("activate_timer");$("#gui_content").empty();html_msg='<div id="gui_timers"></div>';$("#gui_content").append(html_msg);for(var b=0;b<timers.length;b++){var a=timers[b].id;if(d==a){var c=timers[b];html_msg='<table border="0">';$("#gui_timers").append(html_msg);var e=$("#gui_timers").children(),f='<thead><tr class="switch"><td><input type="submit" id="'+a+'Fe" value="Store" class="dbuttons play_button" style="min-width:100px;"></td></td><td><input type="input"  id="'+
a+'Fl" value="'+timers[b].name+'" class="dlabels"></td><td></thead>';$(e).append(f);$(e).append("<tbody>");a="<tr>";a+='<td><label for="scene">Select Scene: </label></td>';a+='<td><select id="scene" value="scene" style="font-size:normal;" class="dlabels">';for(g=0;g<scenes.length;g++)a=scenes[g].name==c.scene?a+('<option class="dlabels" value="'+scenes[g].name+'" selected>'+scenes[g].name+"</option>"):a+('<option class="dlabels" value="'+scenes[g].name+'" >'+scenes[g].name+"</option>");a+="</select></td>";
f='<tr class="timer"><form><fieldset name="scene_select">'+a+"<br /></fieldset></form>";$(e).append(f);a=c.tstart.split(":");f='<td><input type="text" id="Tv" value= "';switch(a[0]){case "96":f+="Sunrise - "+30*a[1]+" minutes";break;case "97":f+="Sunrise + "+30*a[1]+" minutes";break;case "98":f+="Sunset - "+30*a[1]+" minutes";break;case "99":f+="Sunset + "+30*a[1]+" minutes";break;default:f+=("00"+a[0]).slice(-2)+":"+("00"+a[1]).slice(-2)}f+='" class="dlabels sval" style="width:120px;">';f+="</td>";
str3="<td>";str3+='<input type="submit" id="Ts" value="Time" class="dbuttons timbut">';str3+='<input type="submit" id="Tr" value="SunRise" class="dbuttons timbut" >';str3+='<input type="submit" id="Td" value="SunSet" class="dbuttons timbut" >';str3+="</select></td>";f='<tr class="timer"><tr><td><label for="tstart">Start time: </label></td>'+f+"<form><fieldset>"+str3+"<br /></fieldset></form></tr>";$(e).append(f);$(".timbut").removeClass("hover");"96"==a[0]||"97"==a[0]?$("#Tr").addClass("hover"):"98"==
a[0]||"99"==a[0]?$("#Td").addClass("hover"):$("#Ts").addClass("hover");a="<td>Start Date: </td>";if(1!=jqmobile)a+='<td><input  class="dlabels" type="text" id="startd" value="'+c.startd+'"/></td>',f='<tr class="timer"><form><fieldset>'+a+"</fieldset></form></tr>",$(e).append(f),$(function(){$("#startd").datepicker({dateFormat:"dd/mm/yy"})});else{var f=c.startd.substr(0,2),h=c.startd.substr(3,2),g=c.startd.substr(6,2),a=a+('<td><input  class="dlabels" type="text" min="2013-12-15" id="startd" value="20'+
g+"-"+h+"-"+f+'"/></td>'),f='<tr class="timer"><form><fieldset>'+a+"</fieldset></form></tr>";$(e).append(f);startd=$("#startd").mobipick({dateFormat:"dd/MM/yy"});startd.on("change",function(){c.startd=$("#startd").val();alert("startd:: "+c.startd)})}a="<td>End Date: </td>";1!=jqmobile?(a+='<td><input  class="dlabels" type="text" id="endd" value="'+c.endd+'"/></td>',f='<tr class="timer"><form><fieldset>'+a+"</fieldset></form></tr>",$(e).append(f),$(function(){$("#endd").datepicker({dateFormat:"dd/mm/y"})})):
(f=c.endd.substr(0,2),h=c.endd.substr(3,2),g=c.endd.substr(6,2),a+='<td><input  class="dlabels" type="text" min="2013-12-15" id="endd" value="20'+g+"-"+h+"-"+f+'"/></td>',f='<tr class="timer"><form><fieldset>'+a+"</fieldset></form></tr>",$(e).append(f),endd=$("#endd").mobipick({dateFormat:"dd/MM/yy"}),endd.on("change",function(){c.endd=$("#endd").val()}));for(var a='<td colspan="3"><br /><div class="days">',f="Mon Tue Wed Thu Fri Sat Sun".split(" "),g=0;7>g;g++)a="x"!=c.days.substr(g,1)?a+(" "+f[g]+
'<input type="checkbox" id="'+g+'" name="'+f[g]+'" value="'+g+'" checked="checked" >'):a+(" "+f[g]+'<input type="checkbox" id="'+g+'" name="'+f[g]+'" value="'+g+'" >');a+="</div></td>";f='<tr><td colspan="3"><p>On what days of the week?</p></td></tr>';f+='<tr class="timer">'+a+"<br></tr>";$(e).append(f);a='<tr><td colspan="3"><a>What months should the timer run?</a></td></tr>';a+='<tr class="timer"><td colspan="3"><br /><div class="months">';h="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");
for(g=0;12>g;g++)a="x"!=c.months.substr(g,1)?a+(" "+h[g]+'<input type="checkbox" id="'+g+'" name="'+h[g]+'" value="'+g+'" checked="checked">'):a+(" "+h[g]+'<input type="checkbox" id="'+g+'" name="'+h[g]+'" value="'+g+'">');a+="</div></td><br></tr>";$(e).append(a);$("#gui_timers").on("click",".dbuttons",function(a){a.preventDefault();value=$(this).val();a=$(a.target).attr("id");var b=get_timer(s_timer_id);switch(a.substr(-2)){case "Fe":var c=$.map($(".days :input:checkbox:checked"),function(a,b){return+a.value}),
d="xxxxxxx";a="mtwtfss";for(var e=0;e<c.length;e++)d=d.substr(0,c[e])+a.substr(c[e],1)+d.substr(c[e]+1);b.days=d;c=$.map($(".months :input:checkbox:checked"),function(a,b){return+a.value});d="xxxxxxxxxxxx";a="jfmamjjasond";for(e=0;e<c.length;e++)d=d.substr(0,c[e])+a.substr(c[e],1)+d.substr(c[e]+1);b.months=d;b.scene=$("#scene").val();b.startd=$("#startd").val();b.endd=$("#endd").val();send_2_dbase("store_timer",b);break;case "Fx":a='!FxP"'+b.name+'"';alert("Delete current Sequence: "+b.name+"\ntimer cmd: "+
a);message_device("timer",a);break;case "Fr":myConfirm("You are about to add a new action to the timer. If you continue, the systemwill be in recording mode until you have selected a device action. Then you are returnedto this timer screen again. Please confirm if you want to add a device.",function(){message('<p style="textdecoration: blink; background-color:red; color:white;">RECORDING</p>')},function(){s_recording=0;return 1},"Adding a Timer action?");s_recording=1;s_recorder="";init_rooms("init");
break;case "Ts":$(".timbut").removeClass("hover");$("#Ts").addClass("hover");for(var f=$("#Tv").val(),c="",e=0;24>e;e++)c=12==e?c+("<option selected>"+("00"+e).slice(-2)+"</option>"):c+("<option>"+("00"+e).slice(-2)+"</option>");a="";for(e=0;60>e;e++)a+="<option>"+("00"+e).slice(-2)+"</option>";a='<form id="addRoomForm"><fieldset><p>You can change the timer settings for this action. Please use hh:mm</p><br /><label for="val_1">hrs: </label><select id="val_1" value="'+f.substr(0,2)+'" >'+c+'</select><label for="val_2">mins: </label><select id="val_2" value="'+
f.substr(3,2)+'">'+a+"</select></fieldset></form>";askForm(a,function(a){2<debug&&alert(" Dialog returned val_1,val_2,val_3: "+a);a=a[0]+":"+a[1];$("#Tv").val(a);b.tstart=a;1<debug&&alert("Timer changed from "+f+" to: "+a);set_timer(s_timer_id,b)},function(){},"Confirm Change");break;case "Tr":$(".timbut").removeClass("hover");$("#Tr").addClass("hover");f=$("#Tv").val();a="";for(e=-4;5>e;e++)a=0==e?a+("<option selected>"+30*("00"+e).slice(-2)+"</option>"):a+("<option>"+30*("00"+e).slice(-2)+"</option>");
a='<form id="addRoomForm"><fieldset><p>Setting the timer to start at SunRise</p><br /><label for="val_1">Sunrise offset in minutes: </label><select id="val_1" value="'+f.substr(3,2)+'">'+a+"</select></fieldset></form>";askForm(a,function(a){2<debug&&alert(" Dialog returned val_1,val_2,val_3: "+a);0>a[0]?(laval="SunRise - "+a[0].substr(1)+" minutes",b.tstart="96:"+("00"+a[0]/-30).slice(-2)):(laval="SunRise + "+a[0]+" minutes",b.tstart="97:"+("00"+a[0]/30).slice(-2));$("#Tv").val(laval);1<debug&&alert("Timer changed from "+
f+" to: "+laval);set_timer(s_timer_id,b)},function(){},"Set Sunrise Timer");break;case "Td":$(".timbut").removeClass("hover");$("#Td").addClass("hover");f=$("#Tv").val();a="";for(e=-4;5>e;e++)a=0==e?a+("<option selected>"+30*("00"+e).slice(-2)+"</option>"):a+("<option>"+30*("00"+e).slice(-2)+"</option>");a='<form id="addRoomForm"><fieldset><p>Setting the timer to start at SunSet</p><br /><label for="val_1">Sunset offset in minutes: </label><select id="val_1" value="'+f.substr(3,2)+'">'+a+"</select></fieldset></form>";
askForm(a,function(a){2<debug&&alert(" Dialog returned val_1,val_2,val_3: "+a);0>a[0]?(laval="SunSet - "+a[0].substr(1)+" minutes",b.tstart="98:"+("00"+a[0]/-30).slice(-2)):(laval="SunSet + "+a[0]+" minutes",b.tstart="99:"+("00"+a[0]/30).slice(-2));$("#Tv").val(laval);1<debug&&alert("Timer changed from "+f+" to: "+laval);0>set_timer(s_timer_id,b)&&alert("Cannot set timer values in object")},function(){},"Set Sunset Timer");break;case "Tv":$("#Ts").hasClass("hover")&&alert("Ts time");$("#Tr").hasClass("hover")&&
alert("Tr sunrise");$("#Td").hasClass("hover")&&alert("Td sunsetk");break;default:alert("Sequence action unknown: "+a.substr(-2))}})}}s_timer_id=d}
function activate_setting(d){$("#gui_content").empty();switch(d){case "0":html_msg='<table border="0">';$("#gui_content").append(html_msg);d=$("#gui_content").children();var b='<tr class="switch"><td>Select the debug level: </td>';$(d).append(b);b='<td><span id="choice" class="buttonset"><input type="radio" name="choice" id="d0" value="0" class="buttonset" checked="checked"><label for="d0">L0</label><input type="radio" name="choice" id="d1" value="1" class="buttonset" ><label for="d1">L1</label><input type="radio" name="choice" id="d2" value="2" class="buttonset" ><label for="d2">L2</label><input type="radio" name="choice" id="d3" value="3" class="buttonset" ><label for="d3">L3</label></span></td>';$(d).append(b);
b=" <br>This is some text to explain the use of the debug parameter. During normal operation, the parameter should  be set to 0, which means no debug messages are displayed and only a condensed set of status messages will be shown. <li>Level 1: Will set debug level so that more messages are displayed in the message area <li>Level 2: Will add popup alerts for the main things/buttons/events <li>Level 3: All error and comment messages are displayed <br /><br> ";$(d).append("<tr><td><span>"+b+"</span>");
debug=settings[0].val;$("#choice").buttonset();$("#d"+debug).attr("checked",!0).button("refresh");$("#choice input[type=radio]").change(function(){debug=this.value;settings[0].val=debug;0<persist&&(0<debug&&myAlert("Set : "+settings[0].name+" to "+settings[0].val,"DEBUG LEVEL"),send_2_dbase("store_setting",settings[0]));message("debug level set to "+debug)});break;case "1":html_msg='<table border="0">';$("#gui_content").append(html_msg);d=$("#gui_content").children();b='<tr class="switch"><td>Select which controller to use: </td>';
$(d).append(b);b=1==jqmobile?'<td><div data-role="controlgroup" data-type="horizontal"><input type="radio" name="choice" id="d0" value="0" class="buttonset" checked="checked"><label for="d0">ICS-1000</label><input type="radio" name="choice" id="d1" value="1" class="buttonset"><label for="d1">Raspberry</label></div></td>':'<td><span id="choice" class="buttonset"><input type="radio" name="choice" id="d0" value="0" class="buttonset" checked="checked"><label for="d0">ICS-1000</label><input type="radio" name="choice" id="d1" value="1" class="buttonset"><label for="d1">Raspberry</label></span></td>';
$(d).append(b);b="<br> This parameter describes which controller we will use to send lamp commands to the devices. The ICS-1000 is a safe choice in case you have one. For users that have a Raspberry PIand a 433 MHz transmitter (and implemented the commands as found in backend_rasp.php it's much more fun to use the latter. Remember to pair your device with either or both.<br /><br> ";$(d).append("<tr><td><span>"+b+"</span>");cntrl=settings[1].val;1==jqmobile?($("#d"+cntrl).attr("checked",!0).button("refresh"),
$(".buttonset").bind("click",function(a,b){cntrl=$(a.target).val();0==cntrl?(alert("Setting controller to ICS-1000"),s_controller=murl+"backend_ics.php"):(alert("Setting controller to Raspberry"),s_controller=murl+"backend_rasp.php");message("Controller value value set to "+cntrl);settings[1].val=cntrl;0<persist&&send_2_dbase("store_setting",settings[1])})):($("#choice").buttonset(),$("#d"+cntrl).attr("checked",!0).button("refresh"),$("#choice input[type=radio]").change(function(a){cntrl=this.value;
0==cntrl?(myAlert("Setting controller to ICS-1000"),s_controller=murl+"backend_ics.php"):(myAlert("Setting controller to Raspberry"),s_controller=murl+"backend_rasp.php");message("Controller value value set to "+cntrl);settings[1].val=cntrl;0<persist&&(1<debug&&alert("Set : "+settings[1].name+" to "+settings[1].val),send_2_dbase("store_setting",settings[1]))}));break;case "2":html_msg='<table border="0">';$("#gui_content").append(html_msg);d=$("#gui_content").children();b='<tr class="switch"><td>Select SQL use or plain files: </td>';
$(d).append(b);b='<td><span id="choice" class="buttonset"><input type="radio" name="choice" id="d0" value="0" class="buttonset"><label for="d0">Files</label><input type="radio" name="choice" id="d1" value="1" class="buttonset" checked="checked"><label for="d1">SQL</label></span></td>';$(d).append(b);b="<br> This parameter describes what kind of storage we use on the backend. The simplest solution is using files for storage, but then we will not be able tosynchronize all ations on the client with storage. <br><br>At the moment, only MySQL is implemented! (and it works like a charm)<br /><br> ";
$(d).append("<tr><td><span>"+b+"</span>");mysql=settings[2].val;$("#choice").buttonset();$("#d"+mysql).attr("checked",!0).button("refresh");$("#choice input[type=radio]").change(function(){mysql=this.value;settings[2].val=mysql;0<persist&&(0<debug&&alert("Set : "+settings[2].name+" to "+settings[2].val),send_2_dbase("store_setting",settings[2]));message("MySQL value set to "+mysql)});break;case "3":html_msg='<table border="0">';$("#gui_content").append(html_msg);d=$("#gui_content").children();b='<tr class="switch"><td>Select persistence to the database: </td>';
$(d).append(b);b='<td><span id="choice" class="buttonset"><input type="radio" name="choice" id="d0" value="0" class="buttonset"><label for="d0">Easy</label><input type="radio" name="choice" id="d1" value="1" class="buttonset" checked="checked"><label for="d1">Relaxed</label><input type="radio" name="choice" id="d2" value="2" class="buttonset"><label for="d2">Strict</label></span></td>';$(d).append(b);b="<br> This parameter deals with the persistence of the data to the SQL database. <li>Easy: Button changes are locally saved, and will be remembered in this session. Configuration changes to scenes/timers are saved to memory only. Re-ordering buttons in sequences are cosmetic only, as soon as you move away from the page changes are forgotten <li>Relaxed: Changes in devices are remembered during the session and are written to the backend changes in sequences are not. When other users use remotes or other jqmobile apps,relaxed still has advantages, although remembering buttons settings between sessions is less useful<li>Strict: As far as possible, every change in configuration data will be written to the backend database. More traffic overhead, slower performance, but maximum consistency of the database also between different webusers or sessions.";
$(d).append("<tr><td><span>"+b+"</span>");persist=settings[3].val;$("#choice").buttonset();$("#d"+persist).attr("checked",!0).button("refresh");$("#choice input[type=radio]").change(function(){persist=this.value;settings[3].val=persist;message("Persist value set to "+persist);0<=persist&&(0<debug&&alert("Set : "+settings[3].name+" to "+settings[3].val),send_2_dbase("store_setting",settings[3]))});break;case "4":$("#gui_content").empty();html_msg='<div id="gui_skin"></div>';$("#gui_content").append(html_msg);
html_msg='<table border="0">';$("#gui_skin").append(html_msg);d=$("#gui_skin").children();b='<thead><tr class="switch"><td colspan="2">Choose your Style/Skin setting </td></tr></thead>';$(d).append(b);b="This option allows you to set the skin for your LamPI application. It will allow you to make your own selection of skins in a /styles/yourskin.css file, and make it the style of choice for your setting.<br><br>";b+="Note: Not supportted on mobile devices!<br>";b+="Note: Better not choose a files for use on mobile devices ...<br><br>";
$(d).append('<tr><td colspan="2"><span>'+b+"</span>");for(var b='<fieldset><label for="load_skin">Select File: </label><select id="load_skin" value="styles/classic-blue.css" style="width:200px;" class="dlabels">',a={},a=send_2_set("list_skin","*css"),c=0;c<a.length;c++)b+="<option>"+a[c]+"</option>";b+="</select></fieldset>";b='<tr><td><input type="submit" name="load_button" id="d1" value="load" class="dbuttons cc_button"><label for="d1">Load Configuration</label><td><form action="">'+b+"</form></td></tr>";
$(d).append(b);$("#gui_skin").on("click",".dbuttons",function(a){a=this.value;message("Skin selected "+a);switch(a){case "load":a=$("#load_skin").val();$("link[href^='styles']").attr("href",a);settings[4].val=a;send_2_dbase("store_setting",settings[4]);break;default:myAlert("Unknown option for Skin/Styles Setting: "+bak)}});break;case "5":$("#gui_content").empty();html_msg='<div id="gui_backup"></div>';$("#gui_content").append(html_msg);html_msg='<table border="0">';$("#gui_backup").append(html_msg);
d=$("#gui_backup").children();b='<thead><tr class="switch"><td colspan="2">What Backup or Restore action can we organize for you </td></tr></thead>';$(d).append(b);b="<br> This page allows you to perform some backup and restore functions.<br>It allows you to restore your database to a previous/known state,for example if you messed up.<br>Making regular backups of your configuration to file will greatly help in restoring to a useful state if something goes wrong.<br /><br />The database.cfg file is one of the default files for the system, so please use another name for your backup.<br/><br/>NOTE: At this moment we do not check for overwriting existing files.<br/>";
$(d).append('<tr><td colspan="2"><span>'+b+"</span></td>");b='<fieldset><label for="load_config">Select File: </label><select id="load_config" value="load" class="dlabels" style="width:200px;">';a={};a=send_2_set("list_config","*cfg");b+="<option>   </option>";for(c=0;c<a.length;c++)b+="<option>"+a[c]+"</option>";b+="</select>";b+="</fieldset>";b='<tr><td><input type="submit" name="store_button" id="d0" value="store" class="dbuttons buttonset"><label for="d0">Backup the configuration</label></td><td><fieldset>To File &nbsp&nbsp:&nbsp&nbsp<input type="input" id="store_config" value="" class="dlabels" style="width:200px;"></fieldset></td></tr><tr><td><input type="submit" name="load_button" id="d1" value="load" class="dbuttons cc_button"><label for="d1">Load Configuration</label><td><form action="">'+
b+"</form></td></tr>";$(d).append(b);$("#gui_backup").on("click",".dbuttons",function(a){bak=this.value;message("Backup Restore function chosen "+bak);switch(bak){case "store":a=$("#store_config").val();".cfg"!=a.substr(-4)&&(a+=".cfg");send_2_set("store_config",a);0<debug&&myAlert("Backup: "+a);break;case "load":a=$("#load_config").val();send_2_set("load_config",a);0<debug&&myAlert("The configuration file is now set to: "+a,"CONFIGURATION");break;default:myAlert("Unknown option for Backup Setting: "+
bak)}});break;default:myAlert("Config encountered internal error: unknown button")}}function room_button(d,b,a){return'<input type="submit" id="'+d+'" value= "'+b+'" class="hr_button '+a+'">'}function scene_button(d,b,a){return'<input type="submit" id="'+d+'" value= "'+b+'" class="hs_button '+a+'">'}function menu_button(d,b,a){return'<td><input type="submit" id="'+d+'" value= "'+b+'" class="hm_button '+a+'"></td>'}
function timer_button(d,b,a){return'<input type="submit" id="'+d+'" value= "'+b+'" class="ht_button '+a+'">'}function handset_button(d,b,a){return'<input type="submit" id="'+d+'" value= "'+b+'" class="hh_button '+a+'">'}function setting_button(d,b,a){return'<input type="submit" id="'+d+'" value= "'+b+'" class="hc_button '+a+'">'}
function store_device(d,b,a){for(var c=0;c<devices.length;c++){var e=devices[c].id;if(devices[c].room==d&&e==b){d=devices[c].type;"OFF"==a&&"switch"==d?devices[c].val=0:"ON"==a&&"switch"==d?devices[c].val=1:"ON"==a&&"dimmer"==d?devices[c].val=devices[c].lastval:"OFF"==a&&"dimmer"==d?devices[c].val=0:(devices[c].val=a,devices[c].lastval=a);break}}return 1}function find_device(d,b){for(var a=0;a<devices.length;a++){var c=devices[a].id;if(devices[a].room==d&&c==b)return a}return-1}
function load_device(d,b){for(var a=0;a<devices.length;a++){var c=devices[a].id;if(devices[a].room==d&&c==b)return devices[a].val}return 1}function get_scene(d){for(var b=0;b<scenes.length;b++)if(scenes[b].id==d)return scenes[b];return 1}function get_handset(d){for(var b=0;b<handsets.length;b++)if(handsets[b].id==d)return handsets[b];return 1}
function get_handset_record(d,b,a){for(var c=0;c<handsets.length;c++)if(handsets[c].id==d&&handsets[c].unit==b&&handsets[c].val==a)return handsets[c];return 1}function get_timer(d){for(var b=0;b<timers.length;b++)if(timers[b].id==d)return timers[b];return-1}function set_timer(d,b){for(var a=0;a<timers.length;a++)if(timers[a].id==d)return timers[a]=b,0;return-1}
function handle_device(d,b){var a="!R"+s_room_id+d;2<debug&&alert("handle_device:: \nstr: "+a+"\nval: "+b);switch(b){case "Fo":a+="Fo";break;case "ON":case "F1":for(var c=0;c<devices.length;c++)if(devices[c].id==d&&devices[c].room==s_room_id){a="dimmer"==devices[c].type?a+"FdP"+devices[c].lastval:a+"F1";break}break;case "OFF":case "F0":a+="F0";break;case "DUP":a+="S1";break;case "D":alert("handle_device:: "+b+" command not recognized");break;default:a+=b}for(var e="",c=0;c<devices.length;c++)if(devices[c].id==
d.substr(0,2)&&devices[c].room==s_room_id){e=brands[devices[c].brand].fname;break}console.log("handle_device:: lamp code is: "+a);message_device(e,a)}
function decode_scene_string(d){1<debug&&console.log("decode_scene_string: "+d);var b,a,c,e;b=0;switch(d.substr(b,1)){case "!":b++;e="";"R"==d.substr(b,1)?(b++,c=d.substr(b+1,1),"D"==c||"F"==c?(a=d.substr(b,1),b++):(a=d.substr(b,2),b+=2)):alert("decode_scene: Room not found in command string");for(var f=0;f<rooms.length;f++)rooms[f].id==a&&(e+=rooms[f].name);if("D"==d.substr(b,1)){e+=", ";b++;"F"==d.substr(b+1,1)?(c=d.substr(b,1),b++):(c=d.substr(b,2),b+=2);for(f=0;f<devices.length;f++)if(devices[f].id==
"D"+c&&devices[f].room==a)switch(e+=devices[f].name,devices[f].type){case "dimmer":e+=", dimmer";break;case "switch":e+=", switch";break;default:alert("decode_scene:: Unsupported devicetype: "+devices[f].type)}if("F"==d.substr(b,1))switch(b++,a=d.substr(b,1),a){case "a":e+=", ALL OFF";break;case "o":e+=", set dimmer";break;case "0":e+=", OFF";break;case "1":e+=", ON";break;case "k":e+=", Man. Lock";break;case "l":e+=", Full Lock";break;case "d":b++,"P"==d.substr(b,1)&&(b++,e+=", dim value: "+d.substr(b))}}else"F"==
d.substr(b,1)?e+=", All off":alert("Unknown syntax: "+c+" at this position. cmd:: "+d);break;case "0":e="Timing delay "+d.substr(1)}return e}
function load_database(d){var b=murl+"backend_sql.php";1<debug&&alert("load_database:: sqlServer:: "+b);$.ajax({url:b,async:!1,type:"POST",dataType:"json",data:{action:"load_database",message:d},timeout:6E3,success:function(a){rooms=a.appmsg.rooms;devices=a.appmsg.devices;scenes=a.appmsg.scenes;timers=a.appmsg.timers;handsets=a.appmsg.handsets;settings=a.appmsg.settings;brands=a.appmsg.brands;$("#gui_header").append('<table border="0">');$("#gui_header").children();init();1<debug&&alert("Ajax call init_dbase success. \nTransaction Nr: "+
a.tcnt+",\nStatus: "+a.status+".\nApp Msg: "+a.appmsg+".\nApp Err: "+a.apperr);but="Init function success";1<debug&&(but+="<br>AppErr: "+a.apperr);message(but);return 0},error:function(a,c,e){1<debug?alert("load_database:: Error "+b+" sending cmd:: "+d+"\nError: "+a.status+"\nTextStatus: "+c+"\nerrorThrown: "+e+"\n\nFunction will finish now!"):alert("Timeout connecting to database on "+b);return-1}})}
function message_device(d,b){if(s_recording)return s_recorder+=b,activate_scene(s_scene_id),1;if(1==phonegap||0==settings[1].val)$.ajax({url:s_controller,type:"POST",dataType:"json",data:{action:d,message:b},timeout:5E3,success:function(a){switch(a.status){case "OK":var c="Dev cmd "+b+" <br>Status: "+a.status+", Return: "+a.appmsg;0<debug&&(c+="\nAppErr: "+a.apperr);message(c);break;case "ERR":c="Dev cmd:"+d+","+b+" <br>Status: "+a.status+" Error: "+a.apperr,message(c)}1<debug&&myAlert("message_device: "+
d+"\ntransaction:"+a.tcnt+"\nStatus: "+a.status+"\n\nApp Msg: "+a.appmsg+"\n\nApp Err: "+a.apperr)},error:function(a,c,h){myAlert("Message_device Error on "+d+"\ncontroller_cmd: "+b+"\njqXHR: "+a+"\ntextstatus"+c+", "+h)}});else if(1!=phonegap&&1==settings[1].val){console.log("websockets:: sending "+b);for(var a={tcnt:++w_tcnt%1E3,action:"gui",message:b},c=0;4>c;c++)switch(w_sock.readyState){case 0:console.log("Websocket:: readystate not ready: "+w_sock.readyState);break;case 1:return w_sock.send(JSON.stringify(a)),
0;case 2:break;case 3:console.log("Websocket:: readystate closed: "+w_sock.readyState);w_sock=WebSocket(w_uri);console.log("Websocket:: socket re-opened: "+w_sock.readyState);break;default:console.log("Websocket:: readystate not defined: "+w_sock.readyState)}console.log("Websocket:: unable to transmit message 3 times: "+w_sock.readyState)}else message("message_device:: xmit faked")}
function send_2_dbase(d,b){$.ajax({url:murl+"backend_sql.php",type:"POST",dataType:"json",data:{action:d,message:b},timeout:8E3,success:function(a){0<debug&&message("Send 2 dbase:: Success");1<debug&&alert("Ajax call send_2_dbase: "+d+" success: \n,\nStatus: "+a.status+".\nApp Msg: "+a.appmsg+".\nApp Err: "+a.apperr);message(a.appmsg)},error:function(a,b,d){alert("send_2_dbase:: request failed \nError: "+a.responseText+"\nTextStatus: "+b+"\nerrorThrown: "+d+"\n\nFunction will finish now!");return-1}})}
function send_2_set(d,b){var a={};$.ajax({async:!1,url:murl+"backend_set.php",type:"POST",dataType:"json",data:{action:d,message:b},timeout:7E3,success:function(b){0<debug&&message("send_2_set:: Success");1<debug&&alert("Ajax call send_2_set success: \n,\nStatus: "+b.status+".\nApp Msg: "+b.appmsg+".\nApp Err: "+b.apperr);return a=b.appmsg},error:function(a,b,f){alert("send_2_set:: command: "+d+"\nError:"+a+"\nTextStatus: "+b+"\nerrorThrown: "+f+"\n\nFunction will finish now!");return-1}});2<debug&&
alert("send_2_set:: returning"+a);return a};