#!/bin/bash
#
#
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pi:/home/pi/scripts:/home/pi/exe"; export PATH
export DISPLAY=:0
#
EXEDIR="/home/pi/exe"; export EXEDIR
SCRIPTDIR="/home/pi/scripts"; export SCRIPTDIR
SENSOR="1w-sensor"; export SENSOR
HOSTNAME="255.255.255.255"; export HOSTNAME
PORTNUMBER="5001"; export PORTNUMBER
#
LOGDIR="/home/pi/log"; export LOGDIR
LOGFILE="$LOGDIR/$0.log"; export LOGFILE
PID=""; export PID

# If we specify the -r (restart) argument on the commandline
# we first kill the running program and then start again
if [ "$1" = "-r" ]; then
	echo "`/bin/date`:: Kill previous version of $SENSOR" >> $LOGFILE 2>&1
	pkill $SENSOR
fi


# Load the required module for the 1-wire sensor program
#
cat /proc/modules | fgrep w1_therm > /dev/null
if [ $? = 0 ]; then
	echo "Module loaded"
else
	sudo modprobe w1_therm
    sudo modprobe w1_gpio
fi

echo "---------------------------------------------------" >> $LOGFILE 2>&1
echo "`date`:: Starting $SENSOR" >> $LOGFILE 2>&1

# Find out whether we have a HOSTNAME in the config file
# If so, we use that name for the Daemon server instead of localhost
	TMP=`grep -Po '(?<=^SERVER=).*' $SCRIPTDIR/PI-config.txt`
	# Find out whether we have a HOSTNAME in the config file
	# If so, we use that name for the Daemon server instead of localhost
	if [ $? = 0 ]; then
		HOSTNAME = $TMP
		echo "Hostname of server found in config file: $HOSTNAME" >> $LOGFILE 2>&1  
	else
		echo "Hostname of server not found in config file" >> $LOGFILE 2>&1
	fi

# Execute the program
# 
cd $EXEDIR

#nohup ./$SENSOR -d -v -h $HOSTNAME -p $PORTNUMBER >> $LOGFILE 2>&1 &
nohup ./$SENSOR -d -b -h $HOSTNAME -p $PORTNUMBER >> $LOGFILE 2>&1 &
