#!/bin/sh

echo "compiling bction"
g++ -o bction bction.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling kakuold"
g++ -o kakuold kakuold.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling coco"
g++ -o coco coco.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling action"
g++ -o action action.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling blokker"
g++ -o blokker blokker.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "compiling elro"
g++ -o elro elro.cpp -I/usr/local/include -L/usr/local/lib -lwiringPi

echo "***** INSTALLING EXECUTABLES IN ../EXE DIR"
mv ./coco ../../exe/coco
mv ./elro ../../exe/elro
mv ./blokker ../../exe/blokker
mv ./kakuold ../../exe/kakuold
mv ./action ../../exe/action

echo "changing permissions"
chown root ../../exe/*
chmod 755 ../../exe/*
chmod u+s ../../exe/*
